import University from "./models/university.model.js";
import mongoose from "mongoose";
import dotenv from "dotenv";

dotenv.config();

const universities = [
  // Dream Universities (Highly Competitive)
  {
    name: "Stanford University",
    country: "USA",
    program: "Computer Science",
    universityType: "Dream",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Stanford_University_campus_aerial_view.jpg/1280px-Stanford_University_campus_aerial_view.jpg",
    ranking: 3,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 60000,
    internshipOpportunities: "Very High",
    placementRate: 98,
    averageSalary: "180000",
    requirements: {
      minGPA: 3.9,
      ielts: 100,
      gre: 330,
      sop: true,
      recommendationLetters: 3
    },
    description: "World's leading tech university, Silicon Valley hub",
    whyItFits: "Perfect for students with strong GPA (3.8+), high test scores, and clear tech goals",
    risks: "Extremely competitive, high cost, location dependency",
    isActive: true
  },
  {
    name: "MIT",
    country: "USA",
    program: "Engineering",
    universityType: "Dream",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/MIT_Dome_in_Cambridge_MA.jpg/1280px-MIT_Dome_in_Cambridge_MA.jpg",
    ranking: 1,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 62000,
    internshipOpportunities: "Very High",
    placementRate: 99,
    averageSalary: "200000",
    requirements: {
      minGPA: 3.95,
      ielts: 105,
      gre: 335,
      sop: true,
      recommendationLetters: 3
    },
    description: "Top engineering and technology institution globally",
    whyItFits: "Ideal for STEM students with exceptional academics",
    risks: "Extremely selective, very high cost, requires perfect test scores",
    isActive: true
  },
  {
    name: "Harvard University",
    country: "USA",
    program: "Business",
    universityType: "Dream",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Harvard_Yard_Widener_Library.jpg/1280px-Harvard_Yard_Widener_Library.jpg",
    ranking: 2,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 60000,
    internshipOpportunities: "Very High",
    placementRate: 99,
    averageSalary: "220000",
    requirements: {
      minGPA: 3.95,
      ielts: 110,
      gre: 330,
      sop: true,
      recommendationLetters: 3
    },
    description: "Ivy League leader, world's most prestigious university",
    whyItFits: "Best for MBA students with strong leadership background",
    risks: "Extremely competitive, high cost, limited international spots",
    isActive: true
  },
  {
    name: "University of Cambridge",
    country: "UK",
    program: "Engineering",
    universityType: "Dream",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/King%27s_College_Chapel%2C_Cambridge_%28UK%29.jpg/1280px-King%27s_College_Chapel%2C_Cambridge_%28UK%29.jpg",
    ranking: 4,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 45000,
    internshipOpportunities: "High",
    placementRate: 97,
    averageSalary: "150000",
    requirements: {
      minGPA: 3.9,
      ielts: 110,
      gre: 325,
      sop: true,
      recommendationLetters: 3
    },
    description: "World's oldest university of continuous operation",
    whyItFits: "Perfect for research-oriented students with strong academics",
    risks: "Highly selective, higher cost for internationals, competitive",
    isActive: true
  },
  {
    name: "University of Oxford",
    country: "UK",
    program: "Law",
    universityType: "Dream",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Radcliffe_Camera%2C_Oxford_-_May_2005.jpg/1280px-Radcliffe_Camera%2C_Oxford_-_May_2005.jpg",
    ranking: 5,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 48000,
    internshipOpportunities: "High",
    placementRate: 97,
    averageSalary: "160000",
    requirements: {
      minGPA: 3.9,
      ielts: 110,
      gre: 320,
      sop: true,
      recommendationLetters: 3
    },
    description: "Prestigious institution with strong heritage",
    whyItFits: "Great for law and humanities students with top academics",
    risks: "Very selective, high cost, interview-heavy process",
    isActive: true
  },

  // Target Universities (Competitive but Achievable)
  {
    name: "University of Toronto",
    country: "Canada",
    program: "Computer Science",
    universityType: "Target",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/University_of_ToroFront_Campus_Centre.jpg/1280px-University_of_ToroFront_Campus_Centre.jpg",
    ranking: 25,
    costLevel: "Medium",
    competitiveness: "High",
    tuitionFeePerYear: 35000,
    internshipOpportunities: "High",
    placementRate: 95,
    averageSalary: "120000",
    requirements: {
      minGPA: 3.6,
      ielts: 95,
      gre: 315,
      sop: true,
      recommendationLetters: 2
    },
    description: "Canada's top university, strong engineering programs",
    whyItFits: "Good fit for students with GPA 3.5+, reasonable test scores",
    risks: "Still competitive, moderate cost",
    isActive: true
  },
  {
    name: "National University of Singapore",
    country: "Singapore",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1606764086407-1e0d0b9b8b4a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 11,
    costLevel: "Medium",
    competitiveness: "High",
    tuitionFeePerYear: 30000,
    internshipOpportunities: "Very High",
    placementRate: 96,
    averageSalary: "110000",
    requirements: {
      minGPA: 3.5,
      ielts: 92,
      gre: 310,
      sop: true,
      recommendationLetters: 2
    },
    description: "Asia's leading university, tech-focused",
    whyItFits: "Perfect for students interested in Asia-Pacific region",
    risks: "Moderate selectivity, lower average salary",
    isActive: true
  },
  {
    name: "University of Melbourne",
    country: "Australia",
    program: "Business",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1578692279837-e95c1b021eb3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 37,
    costLevel: "Medium",
    competitiveness: "Moderate",
    tuitionFeePerYear: 32000,
    internshipOpportunities: "High",
    placementRate: 94,
    averageSalary: "100000",
    requirements: {
      minGPA: 3.4,
      ielts: 90,
      gre: 305,
      sop: true,
      recommendationLetters: 2
    },
    description: "Australia's leading research university",
    whyItFits: "Good choice for moderate GPA students, reasonable cost",
    risks: "Need adequate IELTS, moderate placement rates",
    isActive: true
  },
  {
    name: "University of British Columbia",
    country: "Canada",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1549490349-8643362247b5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 34,
    costLevel: "Medium",
    competitiveness: "Moderate",
    tuitionFeePerYear: 36000,
    internshipOpportunities: "High",
    placementRate: 93,
    averageSalary: "115000",
    requirements: {
      minGPA: 3.5,
      ielts: 93,
      gre: 312,
      sop: true,
      recommendationLetters: 2
    },
    description: "Top Canadian research university in Vancouver",
    whyItFits: "Great balance of prestige and achievability",
    risks: "Moderate competitiveness, higher cost",
    isActive: true
  },
  {
    name: "EPFL (Swiss Federal Institute of Technology)",
    country: "Switzerland",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 20,
    costLevel: "Low",
    competitiveness: "High",
    tuitionFeePerYear: 1500,
    internshipOpportunities: "Very High",
    placementRate: 97,
    averageSalary: "130000",
    requirements: {
      minGPA: 3.6,
      ielts: 95,
      gre: 320,
      sop: true,
      recommendationLetters: 3
    },
    description: "Europe's leading STEM university, low tuition",
    whyItFits: "Excellent for STEM students, very affordable",
    risks: "Competitive, taught in English but some courses in French",
    isActive: true
  },
  {
    name: "IIT Delhi (International Collaborations)",
    country: "India",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1566392241796-3d5b4b3b8b8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 45,
    costLevel: "Low",
    competitiveness: "Moderate",
    tuitionFeePerYear: 5000,
    internshipOpportunities: "High",
    placementRate: 92,
    averageSalary: "80000",
    requirements: {
      minGPA: 3.3,
      ielts: 88,
      gre: 300,
      sop: true,
      recommendationLetters: 2
    },
    description: "India's premier engineering institute, very affordable",
    whyItFits: "Perfect for budget-conscious STEM students",
    risks: "Lower salary outcomes, limited international exposure",
    isActive: true
  },

  // Safe Universities (Achievable with Good Prospects)
  {
    name: "University of Waikato",
    country: "New Zealand",
    program: "Computer Science",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1551286808-9383b9ac5427?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 601,
    costLevel: "Low",
    competitiveness: "Low",
    tuitionFeePerYear: 28000,
    internshipOpportunities: "Moderate",
    placementRate: 85,
    averageSalary: "75000",
    requirements: {
      minGPA: 3.0,
      ielts: 85,
      gre: 290,
      sop: false,
      recommendationLetters: 1
    },
    description: "Good university with open admission, supportive environment",
    whyItFits: "Accessible for students with moderate GPA/scores",
    risks: "Lower ranking and salary outcomes",
    isActive: true
  },
  {
    name: "University of Manitoba",
    country: "Canada",
    program: "Business",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 801,
    costLevel: "Low",
    competitiveness: "Low",
    tuitionFeePerYear: 26000,
    internshipOpportunities: "Moderate",
    placementRate: 82,
    averageSalary: "70000",
    requirements: {
      minGPA: 2.9,
      ielts: 83,
      gre: 285,
      sop: false,
      recommendationLetters: 1
    },
    description: "Welcoming university with good support systems",
    whyItFits: "Good for students below 3.0 GPA, lower test scores",
    risks: "Lower prestige, moderate job prospects",
    isActive: true
  },
  {
    name: "Dublin City University",
    country: "Ireland",
    program: "Engineering",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 601,
    costLevel: "Medium",
    competitiveness: "Low",
    tuitionFeePerYear: 25000,
    internshipOpportunities: "High",
    placementRate: 88,
    averageSalary: "85000",
    requirements: {
      minGPA: 3.0,
      ielts: 84,
      gre: 288,
      sop: false,
      recommendationLetters: 1
    },
    description: "Practical education focused, Dublin location advantage",
    whyItFits: "Good option for moderate students wanting EU location",
    risks: "Lower ranking but good practical exposure",
    isActive: true
  },
  {
    name: "University of Limerick",
    country: "Ireland",
    program: "Business",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 701,
    costLevel: "Medium",
    competitiveness: "Low",
    tuitionFeePerYear: 24000,
    internshipOpportunities: "High",
    placementRate: 87,
    averageSalary: "80000",
    requirements: {
      minGPA: 2.8,
      ielts: 82,
      gre: 280,
      sop: false,
      recommendationLetters: 1
    },
    description: "Supportive environment with good internship opportunities",
    whyItFits: "Accessible for most students, strong job connections",
    risks: "Lower prestige, moderate salary",
    isActive: true
  },
  {
    name: "RMIT University",
    country: "Australia",
    program: "Business",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 401,
    costLevel: "Medium",
    competitiveness: "Low",
    tuitionFeePerYear: 30000,
    internshipOpportunities: "High",
    placementRate: 86,
    averageSalary: "82000",
    requirements: {
      minGPA: 2.9,
      ielts: 85,
      gre: 290,
      sop: false,
      recommendationLetters: 1
    },
    description: "Industry-focused, practical approach to education",
    whyItFits: "Good for career-focused, practical learners",
    risks: "Lower prestige but good job outcomes",
    isActive: true
  },
  {
    name: "Coventry University",
    country: "UK",
    program: "Engineering",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1581078426770-6d336e5de7bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 801,
    costLevel: "Medium",
    competitiveness: "Low",
    tuitionFeePerYear: 29000,
    internshipOpportunities: "High",
    placementRate: 84,
    averageSalary: "78000",
    requirements: {
      minGPA: 2.7,
      ielts: 82,
      gre: 280,
      sop: false,
      recommendationLetters: 1
    },
    description: "Welcoming university with good student support",
    whyItFits: "Accessible option for international students",
    risks: "Lower ranking but improving placement",
    isActive: true
  },
  // Additional Universities
  {
    name: "Stanford University",
    country: "USA",
    program: "Data Science",
    universityType: "Dream",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 3,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 61000,
    internshipOpportunities: "Very High",
    placementRate: 98,
    averageSalary: "185000",
    requirements: {
      minGPA: 3.85,
      ielts: 100,
      gre: 330,
      sop: true,
      recommendationLetters: 3
    },
    description: "Top-tier data science program in Silicon Valley",
    whyItFits: "Perfect for AI/ML enthusiasts with strong fundamentals",
    risks: "Extremely competitive, high tuition, location costs",
    isActive: true
  },
  {
    name: "UC Berkeley",
    country: "USA",
    program: "Computer Science",
    universityType: "Dream",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/UC_Berkeley_Campus_aerial_view.jpg/1280px-UC_Berkeley_Campus_aerial_view.jpg",
    ranking: 5,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 48000,
    internshipOpportunities: "Very High",
    placementRate: 97,
    averageSalary: "175000",
    requirements: {
      minGPA: 3.8,
      ielts: 100,
      gre: 325,
      sop: true,
      recommendationLetters: 3
    },
    description: "Renowned CS program, Bay Area tech hub",
    whyItFits: "Great for CS students with solid academics",
    risks: "Competitive, high cost, large class sizes",
    isActive: true
  },
  {
    name: "Carnegie Mellon University",
    country: "USA",
    program: "Computer Science",
    universityType: "Dream",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Carnegie_Mellon_University_Campus.jpg/1280px-Carnegie_Mellon_University_Campus.jpg",
    ranking: 8,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 62000,
    internshipOpportunities: "Very High",
    placementRate: 97,
    averageSalary: "180000",
    requirements: {
      minGPA: 3.75,
      ielts: 100,
      gre: 320,
      sop: true,
      recommendationLetters: 3
    },
    description: "World's top CS university, Pittsburgh PA",
    whyItFits: "Ideal for software engineering and AI students",
    risks: "Very competitive, high tuition, demanding coursework",
    isActive: true
  },
  {
    name: "University of Toronto",
    country: "Canada",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1606764086407-1e0d0b9b8b4a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 25,
    costLevel: "Medium",
    competitiveness: "High",
    tuitionFeePerYear: 35000,
    internshipOpportunities: "High",
    placementRate: 94,
    averageSalary: "130000",
    requirements: {
      minGPA: 3.5,
      ielts: 90,
      gre: 310,
      sop: true,
      recommendationLetters: 2
    },
    description: "Canada's top university, strong research programs",
    whyItFits: "Excellent value with strong academics",
    risks: "Canadian degree less recognized globally",
    isActive: true
  },
  {
    name: "National University of Singapore (NUS)",
    country: "Singapore",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 15,
    costLevel: "Medium",
    competitiveness: "High",
    tuitionFeePerYear: 32000,
    internshipOpportunities: "Very High",
    placementRate: 96,
    averageSalary: "140000",
    requirements: {
      minGPA: 3.6,
      ielts: 95,
      gre: 315,
      sop: true,
      recommendationLetters: 2
    },
    description: "Asia's top university, strong tech hub",
    whyItFits: "Great for Asia-focused careers",
    risks: "Tropical climate, visa restrictions",
    isActive: true
  },
  {
    name: "University of Melbourne",
    country: "Australia",
    program: "Information Technology",
    universityType: "Target",
    ranking: 37,
    costLevel: "Medium",
    competitiveness: "Medium",
    tuitionFeePerYear: 40000,
    internshipOpportunities: "High",
    placementRate: 93,
    averageSalary: "125000",
    requirements: {
      minGPA: 3.4,
      ielts: 92,
      gre: 305,
      sop: true,
      recommendationLetters: 2
    },
    description: "Australia's leading university, Melbourne tech scene",
    whyItFits: "Good for international students, good placement",
    risks: "Long flight from India, visa costs",
    isActive: true
  },
  {
    name: "ETH Zurich",
    country: "Switzerland",
    program: "Engineering",
    universityType: "Dream",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 6,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 1500,
    internshipOpportunities: "Very High",
    placementRate: 98,
    averageSalary: "160000",
    requirements: {
      minGPA: 3.8,
      ielts: 100,
      gre: 325,
      sop: true,
      recommendationLetters: 3
    },
    description: "Europe's top engineering school, extremely affordable tuition",
    whyItFits: "Best engineering program in Europe, low costs",
    risks: "Competitive, German-taught programs, expensive living",
    isActive: true
  },
  {
    name: "University of British Columbia (UBC)",
    country: "Canada",
    program: "Computer Science",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6b4bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 30,
    costLevel: "Medium",
    competitiveness: "High",
    tuitionFeePerYear: 34000,
    internshipOpportunities: "High",
    placementRate: 92,
    averageSalary: "125000",
    requirements: {
      minGPA: 3.4,
      ielts: 90,
      gre: 310,
      sop: true,
      recommendationLetters: 2
    },
    description: "Canada's west coast leader, tech hub",
    whyItFits: "Strong CS program with good internships",
    risks: "Canadian degree, expensive city",
    isActive: true
  },
  {
    name: "Imperial College London",
    country: "UK",
    program: "Engineering",
    universityType: "Dream",
    image: "https://images.unsplash.com/photo-1581078426770-6d336e5de7bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 9,
    costLevel: "High",
    competitiveness: "Extreme",
    tuitionFeePerYear: 46000,
    internshipOpportunities: "Very High",
    placementRate: 96,
    averageSalary: "155000",
    requirements: {
      minGPA: 3.75,
      ielts: 110,
      gre: 320,
      sop: true,
      recommendationLetters: 3
    },
    description: "UK's top engineering university, London",
    whyItFits: "Best for hardcore engineering students",
    risks: "Very competitive, expensive London",
    isActive: true
  },
  {
    name: "University of California San Diego (UCSD)",
    country: "USA",
    program: "Computer Science",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 20,
    costLevel: "High",
    competitiveness: "High",
    tuitionFeePerYear: 47000,
    internshipOpportunities: "Very High",
    placementRate: 95,
    averageSalary: "165000",
    requirements: {
      minGPA: 3.6,
      ielts: 95,
      gre: 315,
      sop: true,
      recommendationLetters: 2
    },
    description: "Top UC school, San Diego tech ecosystem",
    whyItFits: "Great CS program, good placement",
    risks: "High tuition, competitive",
    isActive: true
  },
  {
    name: "Georgia Institute of Technology",
    country: "USA",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1566392241796-3d5b4b3b8b8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 33,
    costLevel: "High",
    competitiveness: "High",
    tuitionFeePerYear: 35000,
    internshipOpportunities: "Very High",
    placementRate: 94,
    averageSalary: "145000",
    requirements: {
      minGPA: 3.55,
      ielts: 92,
      gre: 310,
      sop: true,
      recommendationLetters: 2
    },
    description: "US's top public engineering university, Atlanta",
    whyItFits: "Strong engineering, good value for money",
    risks: "Competitive, course heavy workload",
    isActive: true
  },
  {
    name: "University of Illinois Urbana-Champaign",
    country: "USA",
    program: "Computer Science",
    universityType: "Target",
    ranking: 42,
    costLevel: "Medium",
    competitiveness: "Medium",
    tuitionFeePerYear: 36000,
    internshipOpportunities: "High",
    placementRate: 93,
    averageSalary: "135000",
    requirements: {
      minGPA: 3.45,
      ielts: 90,
      gre: 305,
      sop: true,
      recommendationLetters: 2
    },
    description: "Strong CS program, Illinois tech hub",
    whyItFits: "Good CS program with decent placement",
    risks: "Cold weather, less prestigious than top schools",
    isActive: true
  },
  {
    name: "University of Amsterdam",
    country: "Netherlands",
    program: "Computer Science",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1551286808-9383b9ac5427?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 65,
    costLevel: "Low",
    competitiveness: "Medium",
    tuitionFeePerYear: 18000,
    internshipOpportunities: "High",
    placementRate: 88,
    averageSalary: "110000",
    requirements: {
      minGPA: 3.2,
      ielts: 85,
      gre: 295,
      sop: false,
      recommendationLetters: 1
    },
    description: "Affordable Netherlands education, English taught",
    whyItFits: "Low cost, good quality education",
    risks: "Smaller internship network than US",
    isActive: true
  },
  {
    name: "University of Waterloo",
    country: "Canada",
    program: "Computer Science",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1578692279837-e95c1b021eb3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 35,
    costLevel: "Medium",
    competitiveness: "High",
    tuitionFeePerYear: 33000,
    internshipOpportunities: "Very High",
    placementRate: 95,
    averageSalary: "135000",
    requirements: {
      minGPA: 3.5,
      ielts: 90,
      gre: 310,
      sop: true,
      recommendationLetters: 2
    },
    description: "Canada's tech hub, best internship program",
    whyItFits: "Exceptional co-op program, tech-focused",
    risks: "Canadian degree, cold weather",
    isActive: true
  },
  {
    name: "Technische Universität München",
    country: "Germany",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 40,
    costLevel: "Low",
    competitiveness: "Medium",
    tuitionFeePerYear: 1200,
    internshipOpportunities: "High",
    placementRate: 90,
    averageSalary: "115000",
    requirements: {
      minGPA: 3.4,
      ielts: 88,
      gre: 300,
      sop: true,
      recommendationLetters: 1
    },
    description: "Germany's top engineering school, very affordable",
    whyItFits: "Top engineering, extremely low tuition",
    risks: "German language required for some programs",
    isActive: true
  },
  {
    name: "University of New South Wales (UNSW)",
    country: "Australia",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 45,
    costLevel: "Medium",
    competitiveness: "Medium",
    tuitionFeePerYear: 42000,
    internshipOpportunities: "High",
    placementRate: 92,
    averageSalary: "128000",
    requirements: {
      minGPA: 3.3,
      ielts: 90,
      gre: 305,
      sop: true,
      recommendationLetters: 2
    },
    description: "Sydney's tech university, growing reputation",
    whyItFits: "Good engineering program, Australian lifestyle",
    risks: "High living costs in Sydney, visa challenges",
    isActive: true
  },
  {
    name: "University of Manchester",
    country: "UK",
    program: "Computer Science",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1566392241796-3d5b4b3b8b8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 60,
    costLevel: "High",
    competitiveness: "Medium",
    tuitionFeePerYear: 44000,
    internshipOpportunities: "High",
    placementRate: 89,
    averageSalary: "120000",
    requirements: {
      minGPA: 3.2,
      ielts: 88,
      gre: 295,
      sop: true,
      recommendationLetters: 1
    },
    description: "Historic CS program, Manchester tech scene",
    whyItFits: "Accessible UK option with decent placement",
    risks: "Lower ranking than Oxford/Cambridge, high cost",
    isActive: true
  },
  {
    name: "Seoul National University",
    country: "South Korea",
    program: "Engineering",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1551286808-9383b9ac5427?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 50,
    costLevel: "Low",
    competitiveness: "Medium",
    tuitionFeePerYear: 12000,
    internshipOpportunities: "High",
    placementRate: 91,
    averageSalary: "125000",
    requirements: {
      minGPA: 3.3,
      ielts: 90,
      gre: 305,
      sop: true,
      recommendationLetters: 1
    },
    description: "Korea's best university, tech hub, very affordable",
    whyItFits: "Top-tier education at low cost",
    risks: "Korean language, cultural adjustment needed",
    isActive: true
  },
  {
    name: "McGill University",
    country: "Canada",
    program: "Computer Science",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1578692279837-e95c1b021eb3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 32,
    costLevel: "Medium",
    competitiveness: "High",
    tuitionFeePerYear: 32000,
    internshipOpportunities: "High",
    placementRate: 93,
    averageSalary: "132000",
    requirements: {
      minGPA: 3.5,
      ielts: 90,
      gre: 310,
      sop: true,
      recommendationLetters: 2
    },
    description: "Montreal's prestigious university, bilingual",
    whyItFits: "Strong CS program in vibrant city",
    risks: "Canadian degree, bilingual environment",
    isActive: true
  },
  {
    name: "University of Copenhagen",
    country: "Denmark",
    program: "Computer Science",
    universityType: "Safe",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 55,
    costLevel: "Low",
    competitiveness: "Medium",
    tuitionFeePerYear: 6000,
    internshipOpportunities: "High",
    placementRate: 87,
    averageSalary: "115000",
    requirements: {
      minGPA: 3.2,
      ielts: 85,
      gre: 290,
      sop: false,
      recommendationLetters: 1
    },
    description: "Scandinavia's best value, tech-friendly",
    whyItFits: "Excellent quality at minimal cost",
    risks: "Expensive living, cold weather",
    isActive: true
  },
  {
    name: "University of Tokyo",
    country: "Japan",
    program: "Engineering",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 28,
    costLevel: "Low",
    competitiveness: "High",
    tuitionFeePerYear: 15000,
    internshipOpportunities: "High",
    placementRate: 92,
    averageSalary: "130000",
    requirements: {
      minGPA: 3.5,
      ielts: 92,
      gre: 310,
      sop: true,
      recommendationLetters: 2
    },
    description: "Asia's top university, tech leader",
    whyItFits: "Top engineering, low cost, safe country",
    risks: "Japanese language, visa requirements",
    isActive: true
  },
  {
    name: "University of Hong Kong",
    country: "Hong Kong",
    program: "Computer Science",
    universityType: "Target",
    image: "https://images.unsplash.com/photo-1566392241796-3d5b4b3b8b8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ranking: 22,
    costLevel: "Medium",
    competitiveness: "High",
    tuitionFeePerYear: 25000,
    internshipOpportunities: "Very High",
    placementRate: 94,
    averageSalary: "140000",
    requirements: {
      minGPA: 3.55,
      ielts: 93,
      gre: 312,
      sop: true,
      recommendationLetters: 2
    },
    description: "Asia's financial hub, strong CS program",
    whyItFits: "High salaries, great city, Asia tech",
    risks: "Political concerns, high living costs",
    isActive: true
  }
];

async function seedUniversities() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    // Clear existing universities
    await University.deleteMany({});
    console.log("Cleared existing universities");

    // Insert new universities
    const result = await University.insertMany(universities);
    console.log(`✅ Seeded ${result.length} universities`);

    await mongoose.disconnect();
    console.log("Disconnected from MongoDB");
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
}

seedUniversities();
